catnet/config/routes.rb
Rails.application.routes.draw do
  get 'cats' => 'cats#index'
  post 'cats/:id/voteup' => 'cats#voteup', as: :voteup_cat

end

catnet/app/models/cat.rb
class Cat < ActiveRecord::Base
end

catnet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

catnet/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
  	@cats = Cat.order(vote_count: :desc)
  end

  def voteup
  	cat = Cat.find(params[:id])
  	cat.vote_count = cat.vote_count + 1
  	cat.save
  	redirect_to cats_path, turbolinks: true
  end
end

catnet/app/helpers/application_helper.rb
module ApplicationHelper
end

catnet/app/helpers/cats_helper.rb
module CatsHelper
end

catnet/app/views/cats/index.html.erb
<div class="container">
	<h1>Cats</h1>
	
	<div class="row">

		
		<% @cats.each_with_index do | cat, index | %>

		  <div class="col-sm-4 col-md-3">
		    <div class="thumbnail">
		      <%= image_tag(cat.url) %>
		      <div class="caption">
		        <h3><%= cat.name %></h3>
		        <p><%= cat.description %></p>
			    <%= form_tag(voteup_cat_path(cat), method: "post") do %>
					<%= submit_tag("Vote Up", class: "btn btn-default") %>
					<%= pluralize(cat.vote_count, 'vote') %>	
				<% end %>
		      </div>
		    </div>
		  </div>

		  <% if (index + 1) % 3 == 0 %>
		    <div class="clearfix visible-sm"></div>
		  <% end %>

		  <% if (index + 1) % 4 == 0 %>
		    <div class="clearfix visible-md visible-lg"></div>
		  <% end %>

		<% end %>

	</div>


</div>

catnet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catnet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>